import type { Priority, Category, Project, Goal, Task, UserSettings, Note, TaskTemplate } from '../types';
import { format, addDays } from 'date-fns';

const today = format(new Date(), 'yyyy-MM-dd');
const tomorrow = format(addDays(new Date(), 1), 'yyyy-MM-dd');
const nextWeek = format(addDays(new Date(), 4), 'yyyy-MM-dd');

export const DEFAULT_PRIORITIES: Priority[] = [
  { id: 'p-low', name: 'Low', color: '#10b981', level: 1, icon: 'ArrowDown' },
  { id: 'p-med', name: 'Medium', color: '#f59e0b', level: 2, icon: 'Minus' },
  { id: 'p-high', name: 'High', color: '#f97316', level: 3, icon: 'ArrowUp' },
  { id: 'p-critical', name: 'Critical', color: '#ef4444', level: 4, icon: 'AlertCircle' },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c-onboarding', name: 'Getting Started', color: '#6366f1', icon: 'Sparkles' },
  { id: 'c-work', name: 'Work', color: '#3b82f6', icon: 'Briefcase' },
  { id: 'c-personal', name: 'Personal', color: '#8b5cf6', icon: 'User' },
  { id: 'c-fitness', name: 'Fitness & Health', color: '#10b981', icon: 'Activity' },
  { id: 'c-study', name: 'Study', color: '#ec4899', icon: 'BookOpen' },
  { id: 'c-projects', name: 'Projects', color: '#06b6d4', icon: 'Folder' },
];

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'dark',
  accentColor: '#6366f1',
  startOfWeek: 1, // Monday
  dateFormat: 'MMM d, yyyy',
  timeFormat: '12h',
  defaultDuration: 30,
  defaultPriorityId: 'p-med',
  notificationsEnabled: false,
};

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: 'proj-onboarding',
    name: 'Getting Started with Daymark',
    description: 'A short tour of the main features of Daymark.',
    color: '#6366f1',
    deadline: format(addDays(new Date(), 7), 'yyyy-MM-dd'),
    notes: 'Complete or remove these tutorial tasks when you are ready to start organizing your own work.',
    createdAt: today,
  },
];

export const DEFAULT_GOALS: Goal[] = [
  {
    id: 'g-onboarding',
    title: 'Explore Daymark',
    type: 'weekly',
    targetCount: 5,
    currentCount: 0,
    unit: 'tasks',
    periodStart: today,
    completed: false,
  },
];

export const DEFAULT_TEMPLATES: TaskTemplate[] = [
  {
    id: 't-1',
    name: 'Morning Focus Routine',
    description: 'Start the workday aligned and clear-headed.',
    tasks: [
      { title: 'Review top 3 daily priorities', priorityId: 'p-high', categoryId: 'c-work', duration: 10 },
      { title: 'Clear inbox and update schedule', priorityId: 'p-med', categoryId: 'c-work', duration: 15 },
      { title: 'Hydrate & 5-minute stretch', priorityId: 'p-low', categoryId: 'c-fitness', duration: 5 },
    ],
  },
];

export const DEFAULT_NOTES: Note[] = [
  {
    id: 'n-onboarding',
    title: 'Welcome Note & Keyboard Shortcuts',
    content: 'Daymark is built for fast, minimal friction planning.\n\nQuick Hotkeys:\n- N : Create new task (Quick Add)\n- F : Toggle Focus Mode\n- D : Open Day View\n- I : Open Inbox\n- Ctrl + K : Global Search',
    categoryId: 'c-onboarding',
    projectId: 'proj-onboarding',
    createdAt: today,
    updatedAt: today,
  },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: 'onboarding-task-1',
    title: 'Welcome to Daymark 👋',
    description: 'This is your first task. Complete it to learn how tasks work. You can edit, reschedule, prioritize, and organize every task you create.',
    dueDate: today,
    dueTime: '09:00',
    duration: 15,
    priorityId: 'p-med',
    categoryId: 'c-onboarding',
    tags: ['onboarding', 'welcome'],
    completed: false,
    isTopPriority: true,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-2',
    title: 'Try setting a priority',
    description: 'Open this task and change its priority. Priorities are color-coded so you can quickly see what needs your attention.',
    dueDate: today,
    dueTime: '10:30',
    duration: 15,
    priorityId: 'p-low',
    categoryId: 'c-onboarding',
    tags: ['priority', 'tutorial'],
    completed: false,
    isTopPriority: true,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-3',
    title: 'Try adding a subtask',
    description: 'Expand this task and add a few subtasks. Subtasks are useful when one task contains several smaller steps.',
    dueDate: today,
    dueTime: '11:45',
    duration: 20,
    priorityId: 'p-med',
    categoryId: 'c-onboarding',
    tags: ['subtasks', 'tutorial'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [
      { id: 'st-ob-1', title: 'Click "Add subtask"', completed: false },
      { id: 'st-ob-2', title: 'Check off a subtask', completed: false },
    ],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-4',
    title: 'Try scheduling a task',
    description: 'Give this task a date and time. Scheduled tasks appear in your Day, Week, Month, and Upcoming views.',
    dueDate: tomorrow,
    dueTime: '14:00',
    duration: 30,
    priorityId: 'p-high',
    categoryId: 'c-onboarding',
    tags: ['schedule', 'tutorial'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-5',
    title: 'Try Quick Add',
    description: 'Press N or use Quick Add to create a task. You can also type something like "Review my notes tomorrow at 6pm high priority".',
    dueDate: tomorrow,
    dueTime: '16:00',
    duration: 15,
    priorityId: 'p-med',
    categoryId: 'c-onboarding',
    tags: ['quick-add', 'tutorial'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-6',
    title: 'Try a recurring task',
    description: 'Set this task to repeat weekly. Completing one occurrence will not complete future occurrences.',
    dueDate: nextWeek,
    dueTime: '10:00',
    duration: 20,
    priorityId: 'p-low',
    categoryId: 'c-onboarding',
    tags: ['recurrence', 'tutorial'],
    completed: false,
    recurrence: {
      frequency: 'weekly',
      interval: 1,
    },
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-7',
    title: 'Create your first project',
    description: 'Projects group related tasks together. Try creating a project and assigning a few tasks to it.',
    dueDate: nextWeek,
    dueTime: '12:00',
    duration: 30,
    priorityId: 'p-med',
    categoryId: 'c-onboarding',
    tags: ['projects', 'tutorial'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-8',
    title: 'Create your first goal',
    description: 'Goals help you track larger objectives over a day, week, or month.',
    dueDate: nextWeek,
    dueTime: '15:00',
    duration: 20,
    priorityId: 'p-med',
    categoryId: 'c-onboarding',
    tags: ['goals', 'tutorial'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'onboarding-task-9',
    title: 'Try Focus Mode',
    description: 'Open Focus Mode to work on one task without distractions. You can use the built-in Pomodoro timer.',
    dueDate: nextWeek,
    dueTime: '16:30',
    duration: 25,
    priorityId: 'p-high',
    categoryId: 'c-onboarding',
    tags: ['focus', 'pomodoro'],
    completed: false,
    projectId: 'proj-onboarding',
    subtasks: [],
    isOnboarding: true,
    createdAt: today,
    updatedAt: today,
  },
];
